export type Program = {
    title: string;
    startTime: string;
    endTime: string;
};

export type Channel = {
    id: number;
    name: string;
    country: string;
    category: string;
    language: string;
    logo: string;
    streamUrl: string;
    tvgId: string;
};

export const channels: Channel[] = [
    {
        id: 0,
        name: "Canal 13",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel0.png",
        streamUrl: "https://redirector.dps.live/hls/13cl/playlist.m3u8",
        tvgId: "Canal.13.de.Chile.cl",
    },
    {
        id: 1,
        name: "T13",
        language: "Spanish",
        country: "Chile",
        category: "News",
        logo: "/channel1.png",
        streamUrl: "https://redirector.rudo.video/hls-video/10b92cafdf3646cbc1e727f3dc76863621a327fd/t13/t13.smil/playlist.m3u8",
        tvgId: "Tele13.Radio.cl",
    },
    {
        id: 2,
        name: "13 Teleseries",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel2.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/f4TrySe8SoiGF8Lu3EIq1g/master.m3u8",
        tvgId: "",
    },
    {
        id: 3,
        name: "13 Kids",
        language: "Spanish",
        country: "Chile",
        category: "Kids",
        logo: "/channel3.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/LhHrVtyeQkKZ-Ye_xEU75g/master.m3u8",
        tvgId: "",
    },
    {
        id: 4,
        name: "TVN",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel4.png",
        streamUrl: "https://iptv2.intersurtv.cl/TVN/index.m3u8",
        tvgId: "Canal.TVN.(Chile).cl",
    },
    {
        id: 5,
        name: "Mega",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel5.png",
        streamUrl: "https://unlimited2-cl-isp.dps.live/mega/mega.smil/playlist.m3u8",
        tvgId: "Canal.Mega.(Chile).cl",
    },
    {
        id: 6,
        name: "TVN 3",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel6.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/5653641561b4eba30a7e4929.m3u8",
        tvgId: "Canal.TVN3.(Chile).cl",
    },
    {
        id: 7,
        name: "13 Realities",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel7.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/g7_JOM0ORki9SR5RKHe-Kw/master.m3u8",
        tvgId: "13Realities.cl",
    },
    {
        id: 8,
        name: "TV Chile",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel8.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/533adcc949386ce765657d7c.m3u8",
        tvgId: "TV.Chile.cl",
    },
    {
        id: 9,
        name: "CHV",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel9.png",
        streamUrl: "https://redirector.rudo.video/hls-video/10b92cafdf3646cbc1e727f3dc76863621a327fd/chv/chv.smil/playlist.m3u8",
        tvgId: "Canal.Chilevisión.(CHV).cl",
    },
    {
        id: 10,
        name: "13 Cultura",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel10.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/GI-9cp_bT8KcerLpZwkuhw/master.m3u8",
        tvgId: "",
    },
    {
        id: 11,
        name: "24 Horas",
        language: "Spanish",
        country: "Chile",
        category: "News",
        logo: "/channel11.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/689ba606ecfe7915e1f8f741.m3u8",
        tvgId: "Canal.24.Horas.(Chile).cl",
    },
    {
        id: 12,
        name: "UCV",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channel12.png",
        streamUrl: "https://unlimited1-cl-isp.dps.live/ucvtv2/ucvtv2.smil/playlist.m3u8",
        tvgId: "Canal.UCV.Televisión.cl",
    },
    {
        id: 20,
        name: "Fox Weather",
        language: "English",
        country: "USA",
        category: "News",
        logo: "/channel20.png",
        streamUrl: "https://247wlive.foxweather.com/stream/index.m3u8",
        tvgId: "",
    },
    {
        id: 21,
        name: "Bloomberg",
        language: "English",
        country: "USA",
        category: "News",
        logo: "/channel21.png",
        streamUrl: "https://www.bloomberg.com/media-manifest/streams/us.m3u8",
        tvgId: "",
    },
    {
        id: 22,
        name: "Telefe",
        language: "Spanish",
        country: "Argentina",
        category: "Entertainment",
        logo: "/channel22.png",
        streamUrl: "http://45.134.141.161:2200/ARG/TELEFE_HD/index.m3u8",
        tvgId: "",
    },
    {
        id: 23,
        name: "Telemax",
        language: "Spanish",
        country: "Argentina",
        category: "Entertainment",
        logo: "/channel23.png",
        streamUrl: "https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/main.m3u8",
        tvgId: "",
    },
    {
        id: 24,
        name: "Alcarria TV",
        language: "Spanish",
        country: "Mexico",
        category: "Entertainment",
        logo: "/channel24.png",
        streamUrl: "https://cls.alcarria.tv/live/alcarriatv-livestream.m3u8",
        tvgId: "",
    },
    {
        id: 25,
        name: "Las estrellas",
        language: "Spanish",
        country: "Mexico",
        category: "Entertainment",
        logo: "/channel25.png",
        streamUrl: "https://channel01-onlymex.akamaized.net/hls/live/2022749/event01/index.m3u8",
        tvgId: "",
    },
    // {
    //     id: 26,
    //     name: "",
    //     language: "",
    //     country: "",
    //     category: "",
    //     logo: "",
    //     streamUrl: "",
    //     tvgId: "",
    // },
    {
        id: 27,
        name: "France 24",
        language: "Spanish",
        country: "France",
        category: "News",
        logo: "/channel27.png",
        streamUrl: "https://live.france24.com/hls/live/2037220-b/F24_ES_HI_HLS/master_5000.m3u8",
        tvgId: "",
    },
    {
        id: 28,
        name: "Fifa +",
        language: "English",
        country: "",
        category: "Sports",
        logo: "/channel28.png",
        streamUrl: "https://cffda8ff.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U2Ftc3VuZy1nYl9GSUZBUGx1c3dvbWVuX0hMUw/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 29,
        name: "BabyFirst",
        language: "Latin America",
        country: "USA",
        category: "kids",
        logo: "/channel29.png",
        streamUrl: "https://cdn.fast.jwp.services/v1/channel/1_jB6940Ei_TvhvIHDL/manifest.m3u8",
        tvgId: "",
    },
    {
        id: 30,
        name: "Canal Infantil",
        language: "Spanish",
        country: "USA",
        category: "kids",
        logo: "/channel30.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/canalinfantil/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 31,
        name: "Cine Familiar",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel31.png",

        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinefamiliar.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 32,
        name: "Cine Hispano",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel32.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinehispano.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 33,
        name: "Cine Premium",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel33.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinepremium.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 34,
        name: "CMT",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel34.png",
        streamUrl: "http://23.237.104.106:8080/USA_CMT/index.m3u8",
        tvgId: "",
    },
    {
        id: 35,
        name: "Comet",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel35.png",
        streamUrl: "https://fast-channels.sinclairstoryline.com/COMET/index.m3u8",
        tvgId: "",
    },
    {
        id: 36,
        name: "Crime + Investigation",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel36.png",
        streamUrl: "http://23.237.104.106:8080/USA_CRIME_INVESTIGATION/index.m3u8",
        tvgId: "",
    },
    {
        id: 37,
        name: "DHE",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel37.png",
        streamUrl: "https://cablered.iptvperu.tv:1936/cablered/dhe_new/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 38,
        name: "Disney Channel",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channel38.png",
        streamUrl: "http://190.14.10.19:16000/play/a06z/index.m3u8",
        tvgId: "",
    },
    {
        id: 39,
        name: "Disney Junior",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel39.png",
        streamUrl: "http://23.237.104.106:8080/USA_DISNEY_JUNIOR/index.m3u8",
        tvgId: "",
    },
    {
        id: 40,
        name: "Disney XD",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel40.png",
        streamUrl: "http://23.237.104.106:8080/USA_DISNEY_XD/index.m3u8",
        tvgId: "",
    },
    {
        id: 41,
        name: "E!",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel41.png",
        streamUrl: "http://23.237.104.106:8080/USA_E/index.m3u8",
        tvgId: "",
    },
    {
        id: 42,
        name: "E!",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel42.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/entertainment.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 43,
        name: "ESPNU",
        language: "English",
        country: "USA",
        category: "Sports",
        logo: "/channel43.png",
        streamUrl: "http://85.237.89.160:9590/usa-s/ESPN-U-HD/index.m3u8",
        tvgId: "",
    },
    {
        id: 44,
        name: "FOX Deportes",
        language: "Spanish",
        country: "Latin America",
        category: "Sports",
        logo: "/channel44.png",
        streamUrl: "http://23.237.104.106:8080/USA_FOX_DEPORTES/index.m3u8",
        tvgId: "",
    },
    {
        id: 45,
        name: "Kids Street",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channel45.png",
        streamUrl: "http://181.78.121.15:8000/play/a00a/index.m3u8",
        tvgId: "",
    },
    {
        id: 46,
        name: "Cinemax Hits",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel46.png",
        streamUrl: "http://23.237.104.106:8080/USA_MOREMAX/index.m3u8",
        tvgId: "",
    },
    {
        id: 47,
        name: "MTV Live",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel47.png",
        streamUrl: "http://23.237.104.106:8080/USA_MTV_LIVE/index.m3u8",
        tvgId: "",
    },
    {
        id: 48,
        name: "NBA",
        language: "English",
        country: "USA",
        category: "Sports",
        logo: "/channel48.png",
        streamUrl: "https://cdn1.ayitistream.com/NBATV/index.m3u8",
        tvgId: "",
    },
    {
        id: 49,
        name: "Showtime Family",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel49.png",
        streamUrl: "http://23.237.104.106:8080/USA_SHOWTIME_FAMILY/index.m3u8",
        tvgId: "",
    },
    {
        id: 50,
        name: "Sony",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel50.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/sonychannel.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 51,
        name: "Star Channel",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel51.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/StarChannel.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 52,
        name: "Starz Cinema",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel52.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_CINEMA/index.m3u8",
        tvgId: "",
    },
    {
        id: 53,
        name: "Starz Comedy",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel53.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_COMEDY/index.m3u8",
        tvgId: "",
    },
    {
        id: 54,
        name: "Starz Kids & Family",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel54.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_FAMILY/index.m3u8",
        tvgId: "",
    },
    {
        id: 55,
        name: "TeenNick",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel55.png",
        streamUrl: "http://tvsen7.aynascope.net/teennick/index.m3u8",
        tvgId: "",
    },
    {
        id: 56,
        name: "Film & Arts",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel56.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/universalcomedy/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 57,
        name: "Disney Jr.",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channel57.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/universalcrime/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 58,
        name: "Telemundo West",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel58.png",
        streamUrl: "http://168.228.44.241:9997/play/a07g/index.m3u8",
        tvgId: "",
    },
    {
        id: 59,
        name: "FX",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel59.png",
        streamUrl: "http://tvsen7.aynascope.net/fx/index.m3u8",
        tvgId: "",
    },
    {
        id: 60,
        name: "Nick Jr.",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel60.png",
        streamUrl: "http://tvsen7.aynascope.net/nickjr/index.m3u8",
        tvgId: "",
    },
    {
        id: 61,
        name: "Nicktoons",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channel61.png",
        streamUrl: "http://tvsen7.aynascope.net/nicktoons/index.m3u8",
        tvgId: "",
    },
    {
        id: 62,
        name: "Comedy Central",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel62.png",
        streamUrl: "https://tvsen3.aynaott.com/5fUWDMxZ/index.m3u8",
        tvgId: "",
    },
    {
        id: 63,
        name: "History",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel63.png",
        streamUrl: "https://tvsen3.aynaott.com/np3JstRE/index.m3u8",
        tvgId: "",
    },
    {
        id: 64,
        name: "MTV",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel64.png",
        streamUrl: "https://tvsen6.aynaott.com/mtv/index.m3u8",
        tvgId: "",
    },
    {
        id: 65,
        name: "National Geographic",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel65.png",
        streamUrl: "https://tvsen3.aynaott.com/7mm4pwCy/index.m3u8",
        tvgId: "",
    },
    {
        id: 66,
        name: "Fox News",
        language: "English",
        country: "USA",
        category: "News",
        logo: "/channel66.png",
        streamUrl: "https://tvsen6.aynaott.com/foxnews/index.m3u8",
        tvgId: "",
    },
    {
        id: 67,
        name: "HBO Hits",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channel67.png",
        streamUrl: "http://tvsen7.aynascope.net/hbo2/index.m3u8",
        tvgId: "",
    },
    {
        id: 68,
        name: "AMC",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channel68.png",
        streamUrl: "https://amc-amcSpanish-1-us.lg.wurl.tv/playlist.m3u8",
        tvgId: "",
    },
];