export type Program = {
    title: string;
    startTime: string;
    endTime: string;
};

export type Channel = {
    id: number;
    name: string;
    country: string;
    category: string;
    language: string;
    logo: string;
    streamUrl: string;
    tvgId: string;
};

export const channels: Channel[] = [
    {
        id: 1,
        name: "13C",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13c.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/GI-9cp_bT8KcerLpZwkuhw/master.m3u8",
        tvgId: "",
    },
    // {
    //     id: 2,
    //     name: "13 Entretencion",
    //     language: "Spanish",
    //     country: "Chile",
    //     category: "Entertainment",
    //     logo: "/channels/channel.png",
    //     streamUrl: "https://origin.dpsgo.com/ssai/event/BBp0VeP6QtOOlH8nu3bWTg/master.m3u8",
    //     tvgId: "",
    // },
    {
        id: 3,
        name: "13 Festival",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13festival.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/Nftd0fM2SXasfDlRphvUsg/master.m3u8",
        tvgId: "",
    },
    // {
    //     id: 4,
    //     name: "13 Humor",
    //     language: "Spanish",
    //     country: "Chile",
    //     category: "Entertainment",
    //     logo: "/channels/channel.png",
    //     streamUrl: "https://origin.dpsgo.com/ssai/event/cKWySXKgSK-SzlJmESkOWw/master.m3u8",
    //     tvgId: "",
    // },
    {
        id: 5,
        name: "13 Kids",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13kids.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/LhHrVtyeQkKZ-Ye_xEU75g/master.m3u8",
        tvgId: "",
    },
    // {
    //     id: 6,
    //     name: "13 Prime",
    //     language: "Spanish",
    //     country: "Chile",
    //     category: "Entertainment",
    //     logo: "/channels/channel.png",
    //     streamUrl: "https://origin.dpsgo.com/ssai/event/p4mmBxEzSmKAxY1GusOHrw/master.m3u8",
    //     tvgId: "",
    // },
    {
        id: 7,
        name: "13 Realities",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13realities.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/g7_JOM0ORki9SR5RKHe-Kw/master.m3u8",
        tvgId: "",
    },
    // {
    //     id: 8,
    //     name: "13Rec",
    //     language: "Spanish",
    //     country: "Chile",
    //     category: "Entertainment",
    //     logo: "/channels/channel.png",
    //     streamUrl: "http://45.4.1.201:8000/play/a11i/index.m3u8",
    //     tvgId: "",
    // },
    {
        id: 9,
        name: "13 Teleseries",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13teleseries.png",
        streamUrl: "https://origin.dpsgo.com/ssai/event/f4TrySe8SoiGF8Lu3EIq1g/master.m3u8",
        tvgId: "",
    },
    {
        id: 10,
        name: "Canal 13",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/ch13.png",
        streamUrl: "https://redirector.dps.live/hls/13cl/playlist.m3u8",
        tvgId: "Canal.13.de.Chile.cl",
    },
    {
        id: 11,
        name: "Canal Latino",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chcanallatino.png",
        streamUrl: "https://videostream.chileservidores.com:8081/latina/index.m3u8",
        tvgId: "",
    },
    {
        id: 12,
        name: "Chile Channel",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chchilechannel.png",
        streamUrl: "https://v2.tustreaming.cl/chilechannel/index.m3u8",
        tvgId: "",
    },
    {
        id: 13,
        name: "ChileVision",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chCHV.png",
        streamUrl: "https://redirector.rudo.video/hls-video/10b92cafdf3646cbc1e727f3dc76863621a327fd/chv/chv.smil/playlist.m3u8",
        tvgId: "Canal.Chilevisión.(CHV).cl",
    },
    {
        id: 14,
        name: "DW",
        language: "Spanish",
        country: "Chile",
        category: "News",
        logo: "/channels/chdw.png",
        streamUrl: "https://v2.tustreaming.cl/chiloered/index.m3u8",
        tvgId: "",
    },
    {
        id: 15,
        name: "EnerGeek Fan",
        language: "Spanish",
        country: "Chile",
        category: "Kids",
        logo: "/channels/chenergeek.png",
        streamUrl: "https://backend.energeek.cl/webtv/egfanweb/index.m3u8?token=ZZDemoIPTVGH",
        tvgId: "",
    },
    {
        id: 16,
        name: "La Red",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chlared.png",
        streamUrl: "https://tv-mgmt.gtd.cl/bpk-tv/LARED/default/index.m3u8",
        tvgId: "Canal.La.Red.(Chile).cl",
    },
    {
        id: 17,
        name: "Mega",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chmega.png",
        streamUrl: "https://unlimited2-cl-isp.dps.live/mega/mega.smil/playlist.m3u8",
        tvgId: "Canal.Mega.(Chile).cl",
    },
    {
        id: 18,
        name: "Solo TV",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chsolotv.png",
        streamUrl: "https://sproxy.solotv.cl/hls/live/fhd.m3u8",
        tvgId: "",
    },
    {
        //It might be 13Rec. Please check later...
        id: 19,
        name: "T13",
        language: "Spanish",
        country: "Chile",
        category: "News",
        logo: "/channels/chT13.png",
        streamUrl: "https://redirector.dps.live/hls/t13/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 20,
        name: "Love Nature",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chlovenature.png",
        streamUrl: "https://unlimited1-us.dps.live/inet2/inet2.smil/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 21,
        name: "TV Chile",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chTVCHILE.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/533adcc949386ce765657d7c.m3u8",
        tvgId: "TV.Chile.cl",
    },
    {
        id: 22,
        name: "TV Senado",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chtvsenado.png",
        streamUrl: "https://janus-tv-ply.senado.cl/playlist/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 23,
        name: "TV+",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chtv+.png",
        streamUrl: "https://unlimited1-us.dps.live/inet2/inet2.smil/playlist.m3u8",
        tvgId: "",
    },
    // {
    //     id: 24,
    //     name: "TVN",
    //     language: "Spanish",
    //     country: "Chile",
    //     category: "Entertainment",
    //     logo: "/channels/chTVN.png",
    //     streamUrl: "https://iptv2.intersurtv.cl/TVN/index.m3u8",
    //     tvgId: "Canal.TVN.(Chile).cl",
    // },
    {
        id: 25,
        name: "TVN3",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chTVN3.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/5653641561b4eba30a7e4929.m3u8",
        tvgId: "",
    },
    {
        id: 26,
        name: "TVR",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chtvr.png",
        streamUrl: "https://unlimited1-us.dps.live/tvr/tvr.smil/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 27,
        name: "Wapp",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chwapp.png",
        streamUrl: "https://stream.wapptv.cl/video/index.m3u8",
        tvgId: "",
    },
    {
        id: 28,
        name: "Canal 26",
        language: "Spanish",
        country: "Argentina",
        category: "News",
        logo: "/channels/ch26.png",
        streamUrl: "https://stream-gtlc.telecentro.net.ar/hls/canal26hls/main.m3u8",
        tvgId: "",
    },
    {
        id: 29,
        name: "Telemax",
        language: "Spanish",
        country: "Argentina",
        category: "Entertainment",
        logo: "/channels/chtelemax.png",
        streamUrl: "https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/main.m3u8",
        tvgId: "",
    },
    // {
    //     id: 30,
    //     name: "El Trece",
    //     language: "Spanish",
    //     country: "Argentina",
    //     category: "Entertainment",
    //     logo: "/channels/cheltrece.png",
    //     streamUrl: "https://livetrx01.vodgc.net/eltrecetv/index.m3u8",
    //     tvgId: "",
    // },
    {
        id: 31,
        name: "TV Cultura",
        language: "Portuguese",
        country: "Brazil",
        category: "Kids",
        logo: "/channels/chtvcultura.png",
        streamUrl: "https://player-tvcultura.stream.uol.com.br/live/tvcultura.m3u8",
        tvgId: "São.Paulo/SP..Cultura.br",
    },
    {
        id: 32,
        name: "TVE RS",
        language: "Portuguese",
        country: "Brazil",
        category: "Entertainment",
        logo: "/channels/chtve.png",
        streamUrl: "http://streaming.procergs.com.br:1935/tve/stve/playlist.m3u8",
        tvgId: "São.Paulo/SP..TVE.International.br",
    },
    {
        id: 33,
        name: "Las Estrellas",
        language: "Spanish",
        country: "Mexico",
        category: "Entertainment",
        logo: "/channels/chlasestrellas.png",
        streamUrl: "https://channel01-onlymex.akamaized.net/hls/live/2022749/event01/index.m3u8",
        tvgId: "Canal.Las.Estrellas.(Chile).cl",
    },
    {
        id: 34,
        name: "Estrella TV",
        language: "Spanish",
        country: "Mexico",
        category: "Entertainment",
        logo: "/channels/chestrellatv.png",
        streamUrl: "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00567-estrellamedia-estrellatv-estrellamedia/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 35,
        name: "TELE 10 Nayarit",
        language: "Spanish",
        country: "Mexico",
        category: "Entertainment",
        logo: "/channels/chtele10.png",
        streamUrl: "https://live.iplanay.gob.mx/hls/nayarittv.m3u8",
        tvgId: "",
    },
    {
        id: 36,
        name: "Latina",
        language: "Spanish",
        country: "Peru",
        category: "Entertainment",
        logo: "/channels/chlatina.png",
        streamUrl: "https://redirector.rudo.video/hls-video/567ffde3fa319fadf3419efda25619456231dfea/latina/latina.smil/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 37,
        name: "Cosmos TV",
        language: "Spanish",
        country: "Peru",
        category: "Entertainment",
        logo: "/channels/chcosmos.png",
        streamUrl: "https://videoserver.tmcreativos.com:19360/tvcosmos/tvcosmos.m3u8",
        tvgId: "",
    },
    {
        id: 38,
        name: "24h",
        language: "Spanish",
        country: "Spain",
        category: "News",
        logo: "/channels/ch24h.png",
        streamUrl: "https://rtvelivestream.rtve.es/rtvesec/24h/24h_main_dvr.m3u8",
        tvgId: "",
    },
    // {
    //     id: 39,
    //     name: "Paramount Network",
    //     language: "Spanish",
    //     country: "Spain",
    //     category: "Entertainment",
    //     logo: "/channels/ch.png",
    //     streamUrl: "https://jmp2.uk/plu-68d566603d3a9580eb461251.m3u8",
    //     tvgId: "",
    // },
    {
        id: 40,
        name: "NBC News",
        language: "English",
        country: "USA",
        category: "News",
        logo: "/channels/chnbcnews.png",
        streamUrl: "https://d1bl6tskrpq9ze.cloudfront.net/hls/master.m3u8?ads.xumo_channelId=99984003",
        tvgId: "",
    },
    {
        id: 41,
        name: "Drybar Comedy",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/chdrybar.png",
        streamUrl: "https://drybar-drybarcomedy-1-us.samsung.wurl.tv/playlist.m3u8",
        tvgId: "",
    },
    // {
    //     id: 42,
    //     name: "FOX LIVE Now",
    //     language: "English",
    //     country: "USA",
    //     category: "News",
    //     logo: "/channels/ch.png",
    //     streamUrl: "https://fox-foxnewsnow-vizio.amagi.tv/playlist.m3u8",
    //     tvgId: "",
    // },
    {
        id: 43,
        name: "America TeVe",
        language: "Spanish",
        country: "USA",
        category: "News",
        logo: "/channels/chamericatv.png",
        streamUrl: "https://live.gideo.video/americateve2/master.m3u8",
        tvgId: "",
    },
    {
        id: 44,
        name: "Peer TV South Tyrol",
        language: "English",
        country: "UK",
        category: "Documentary",
        logo: "/channels/chpeertv.png",
        streamUrl: "https://iptv.peer.biz/live/peertv-en.m3u8",
        tvgId: "",
    },
    {
        id: 45,
        name: "Action Hollywood Movies",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/chactionh.png",
        streamUrl: "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-actionhollywood-samsungnz/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 46,
        name: "France 24 Espanol",
        language: "Spanish",
        country: "International",
        category: "News",
        logo: "/channels/chfrance24.png",
        streamUrl: "https://live.france24.com/hls/live/2037220-b/F24_ES_HI_HLS/master_5000.m3u8",
        tvgId: "",
    },
    {
        id: 47,
        name: "DW",
        language: "Spanish",
        country: "International",
        category: "News",
        logo: "/channels/chdw.png",
        streamUrl: "https://dwamdstream104.akamaized.net/hls/live/2015530/dwstream104/stream04/streamPlaylist.m3u8",
        tvgId: "",
    },
    {
        id: 48,
        name: "RT Espanol",
        language: "Spanish",
        country: "International",
        category: "News",
        logo: "/channels/chrt.png",
        streamUrl: "https://rt-esp.rttv.com/dvr/rtesp/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 49,
        name: "Fifa +",
        language: "English",
        country: "USA",
        category: "Sports",
        logo: "/channels/chfifa.png",
        streamUrl: "https://cffda8ff.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U2Ftc3VuZy1nYl9GSUZBUGx1c3dvbWVuX0hMUw/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 50,
        name: "BabyFirst",
        language: "Latin America",
        country: "USA",
        category: "kids",
        logo: "/channels/chbabyfirst.png",
        streamUrl: "https://cdn.fast.jwp.services/v1/channel/1_jB6940Ei_TvhvIHDL/manifest.m3u8",
        tvgId: "",
    },
    {
        id: 51,
        name: "Canal Infantil",
        language: "Spanish",
        country: "USA",
        category: "kids",
        logo: "/channels/chcanalinfantil.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/canalinfantil/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 52,
        name: "Cine Familiar",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/chcinef.png",

        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinefamiliar.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 53,
        name: "Cine Hispano",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/chcineh.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinehispano.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 54,
        name: "Cine Premium",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/chcinep.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/cinepremium.stream/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 55,
        name: "CMT",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/chcmt.png",
        streamUrl: "http://23.237.104.106:8080/USA_CMT/index.m3u8",
        tvgId: "",
    },
    {
        id: 56,
        name: "Comet",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/chcomet.png",
        streamUrl: "https://fast-channels.sinclairstoryline.com/COMET/index.m3u8",
        tvgId: "",
    },
    {
        id: 57,
        name: "Crime + Investigation",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/chcrime.png",
        streamUrl: "http://23.237.104.106:8080/USA_CRIME_INVESTIGATION/index.m3u8",
        tvgId: "",
    },
    {
        id: 58,
        name: "DHE",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/chdhe.png",
        streamUrl: "https://cablered.iptvperu.tv:1936/cablered/dhe_new/playlist.m3u8",
        tvgId: "Canal.DHE.cl",
    },
    {
        id: 59,
        name: "Disney Channel",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channels/chdisney.png",
        streamUrl: "http://190.14.10.19:16000/play/a06z/index.m3u8",
        tvgId: "Canal.Disney.Channel.(Chile).cl",
    },
    {
        id: 60,
        name: "Disney Junior",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channels/chdisneyj.png",
        streamUrl: "http://23.237.104.106:8080/USA_DISNEY_JUNIOR/index.m3u8",
        tvgId: "Canal.Disney.Junior.(Chile).cl",
    },
    {
        id: 61,
        name: "Disney XD",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channels/chxd.png",
        streamUrl: "http://23.237.104.106:8080/USA_DISNEY_XD/index.m3u8",
        tvgId: "",
    },
    {
        id: 62,
        name: "E!",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel41.png",
        streamUrl: "http://23.237.104.106:8080/USA_E/index.m3u8",
        tvgId: "",
    },
    {
        id: 63,
        name: "E!",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/channel42.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/entertainment.stream/playlist.m3u8",
        tvgId: "Canal.E!.Entertainment.Television.(Chile).cl",
    },
    {
        id: 64,
        name: "ESPNU",
        language: "English",
        country: "USA",
        category: "Sports",
        logo: "/channels/channel43.png",
        streamUrl: "http://85.237.89.160:9590/usa-s/ESPN-U-HD/index.m3u8",
        tvgId: "",
    },
    {
        id: 65,
        name: "FOX Deportes",
        language: "Spanish",
        country: "Latin America",
        category: "Sports",
        logo: "/channels/channel44.png",
        streamUrl: "http://23.237.104.106:8080/USA_FOX_DEPORTES/index.m3u8",
        tvgId: "",
    },
    {
        id: 66,
        name: "Kids Street",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channels/channel45.png",
        streamUrl: "http://181.78.121.15:8000/play/a00a/index.m3u8",
        tvgId: "",
    },
    {
        id: 67,
        name: "Cinemax Hits",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel46.png",
        streamUrl: "http://23.237.104.106:8080/USA_MOREMAX/index.m3u8",
        tvgId: "",
    },
    {
        id: 68,
        name: "MTV Live",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel47.png",
        streamUrl: "http://23.237.104.106:8080/USA_MTV_LIVE/index.m3u8",
        tvgId: "",
    },
    {
        id: 69,
        name: "NBA",
        language: "English",
        country: "USA",
        category: "Sports",
        logo: "/channels/channel48.png",
        streamUrl: "https://cdn1.ayitistream.com/NBATV/index.m3u8",
        tvgId: "",
    },
    {
        id: 70,
        name: "Showtime Family",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel49.png",
        streamUrl: "http://23.237.104.106:8080/USA_SHOWTIME_FAMILY/index.m3u8",
        tvgId: "",
    },
    {
        id: 71,
        name: "Sony",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/channel50.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/sonychannel.stream/playlist.m3u8",
        tvgId: "Canal.Sony.(Chile).cl",
    },
    {
        id: 72,
        name: "Star Channel",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/channel51.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/StarChannel.stream/playlist.m3u8",
        tvgId: "Canal.Star.Channel.(Chile).cl",
    },
    {
        id: 73,
        name: "Starz Cinema",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel52.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_CINEMA/index.m3u8",
        tvgId: "",
    },
    {
        id: 74,
        name: "Starz Comedy",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel53.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_COMEDY/index.m3u8",
        tvgId: "",
    },
    {
        id: 75,
        name: "Starz Kids & Family",
        language: "English",
        country: "USA",
        category: "Kids",
        logo: "/channels/channel54.png",
        streamUrl: "http://23.237.104.106:8080/USA_STARZ_FAMILY/index.m3u8",
        tvgId: "",
    },
    // {
    //     id: 76,
    //     name: "TeenNick",
    //     language: "English",
    //     country: "USA",
    //     category: "Kids",
    //     logo: "/channels/channel55.png",
    //     streamUrl: "http://tvsen7.aynascope.net/teennick/index.m3u8",
    //     tvgId: "",
    // },
    {
        id: 77,
        name: "Film & Arts",
        language: "Spanish",
        country: "Latin America",
        category: "Entertainment",
        logo: "/channels/channel56.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/universalcomedy/playlist.m3u8",
        tvgId: "",
    },
    {
        id: 78,
        name: "Disney Jr.",
        language: "Spanish",
        country: "Latin America",
        category: "Kids",
        logo: "/channels/channel57.png",
        streamUrl: "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/universalcrime/playlist.m3u8",
        tvgId: "Canal.Disney.Junior.(Chile).cl",
    },
    // {
    //     id: 79,
    //     name: "Telemundo West",
    //     language: "Spanish",
    //     country: "Latin America",
    //     category: "Entertainment",
    //     logo: "/channels/channel58.png",
    //     streamUrl: "http://168.228.44.241:9997/play/a07g/index.m3u8",
    //     tvgId: "Canal.Telemundo.(Chile).cl",
    // },
    // {
    //     id: 80,
    //     name: "FX",
    //     language: "English",
    //     country: "USA",
    //     category: "Entertainment",
    //     logo: "/channels/channel59.png",
    //     streamUrl: "http://tvsen7.aynascope.net/fx/index.m3u8",
    //     tvgId: "",
    // },
    // {
    //     id: 81,
    //     name: "Nick Jr.",
    //     language: "English",
    //     country: "USA",
    //     category: "Kids",
    //     logo: "/channels/channel60.png",
    //     streamUrl: "http://tvsen7.aynascope.net/nickjr/index.m3u8",
    //     tvgId: "",
    // },
    // {
    //     id: 82,
    //     name: "Nicktoons",
    //     language: "English",
    //     country: "USA",
    //     category: "Kids",
    //     logo: "/channels/channel61.png",
    //     streamUrl: "http://tvsen7.aynascope.net/nicktoons/index.m3u8",
    //     tvgId: "",
    // },
    // {
    //     id: 83,
    //     name: "Comedy Central",
    //     language: "English",
    //     country: "USA",
    //     category: "Entertainment",
    //     logo: "/channels/channel62.png",
    //     streamUrl: "https://tvsen3.aynaott.com/5fUWDMxZ/index.m3u8",
    //     tvgId: "",
    // },
    {
        id: 84,
        name: "History",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel63.png",
        streamUrl: "https://tvsen3.aynaott.com/np3JstRE/index.m3u8",
        tvgId: "",
    },
    // {
    //     id: 85,
    //     name: "MTV",
    //     language: "English",
    //     country: "USA",
    //     category: "Entertainment",
    //     logo: "/channels/channel64.png",
    //     streamUrl: "https://tvsen6.aynaott.com/mtv/index.m3u8",
    //     tvgId: "",
    // },
    {
        id: 86,
        name: "National Geographic",
        language: "English",
        country: "USA",
        category: "Entertainment",
        logo: "/channels/channel65.png",
        streamUrl: "https://tvsen3.aynaott.com/7mm4pwCy/index.m3u8",
        tvgId: "",
    },
    // {
    //     id: 87,
    //     name: "HBO Hits",
    //     language: "English",
    //     country: "USA",
    //     category: "Entertainment",
    //     logo: "/channels/channel67.png",
    //     streamUrl: "http://tvsen7.aynascope.net/hbo2/index.m3u8",
    //     tvgId: "",
    // },
    // {
    //     id: 88,
    //     name: "AMC",
    //     language: "Spanish",
    //     country: "Latin America",
    //     category: "Entertainment",
    //     logo: "/channels/channel68.png",
    //     streamUrl: "https://amc-amcSpanish-1-us.lg.wurl.tv/playlist.m3u8",
    //     tvgId: "Canal.AMC.(Chile).cl",
    // },
    {
        id: 89,
        name: "24 Horas",
        language: "Spanish",
        country: "Chile",
        category: "News",
        logo: "/channels/ch24horas.png",
        streamUrl: "https://mdstrm.com/live-stream-playlist/689ba606ecfe7915e1f8f741.m3u8",
        tvgId: "Canal.24.Horas.(Chile).cl",
    },
    {
        id: 90,
        name: "UCV",
        language: "Spanish",
        country: "Chile",
        category: "Entertainment",
        logo: "/channels/chucv.png",
        streamUrl: "https://unlimited1-cl-isp.dps.live/ucvtv2/ucvtv2.smil/playlist.m3u8",
        tvgId: "Canal.UCV.Televisión.cl",
    },
];